name: build

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Test lib
        run: |
          npm install
          npm ci
          npm run test

  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci') && github.ref == 'refs/heads/master'"

    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Test lib
        run: |
          npm install
          npm ci
          git checkout master
          npm run test

      - name: Generate CHANGELOG
        run: |
          npm run release
          git push origin master --follow-tags

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
